[package]
name = "test_one_cell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.13.1"
linux-embedded-hal = "0.3.2"
pwm-pca9685 = "0.3.1"
embedded-hal = "0.2.7"